baseURL: "http://yinghei.github.io/ren-relaxing"
languageCode: "en-us"
title: "Ren Relaxing"

# 新增 theme 的名稱
theme: 'PaperMod'

# Profile mode
params:
    profileMode:
        enabled: true
        title: "<Ren Relaxing>" # optional default will be site title
        subtitle: "A | B | C | D"
        imageUrl: "static/black-cat.jpg" # optional
        imageTitle: "<alt for image>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Post
            url: "/post"
          - name: Github
            url: "https://github.com/"

    socialIcons: # optional
      - name: "github"
        url: "https://github.com/YingHei"
      - name: "twitter"
        url: "<link2>"