baseURL: "https://yinghei.github.io/ren-to-ramble"
languageCode: "en-us"
title: "Ren to Ramble"

# 新增 theme 的名稱
theme: 'PaperMod'


params:
    defaultTheme: light
    displayFullLangName: true
    
    # Profile mode
    profileMode:
        enabled: true
        title: "<Ren to Ramble>" # optional default will be site title
        subtitle: "Keep  | Drawing | Productivity"
        imageUrl: "https://raw.githubusercontent.com/yinghei/ren-to-ramble/master/static/img/black-cat.jpg" # optional
        imageTitle: "<alt for image>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Blogs
            url: "posts"
          - name: Gallery
            url: "gallery"

    socialIcons: # optional
      - name: "github"
        url: "https://github.com/YingHei"
      - name: "twitter"
        url: "<link2>"
    
    ShowReadingTime: true

    editPost:
      URL: "https://github.com/YingHei/ren-relaxing/tree/tree/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true
    
# DefaultContentLanguage: zh
languages:
  en:
    languageName: English
    weight: 1
  zh-tw:
    languageName: 繁
    weight: 2

